# Generated by Django 5.2.8 on 2025-12-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
            ],
        ),
    ]
