# Generated by Django 5.2.8 on 2025-12-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('categoria_cnh', models.CharField(max_length=3)),
                ('validade_cnh', models.DateField()),
            ],
        ),
    ]
