# Generated by Django 5.2.8 on 2025-12-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='validade_cnh',
            new_name='cnh_validade',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='categoria_cnh',
        ),
        migrations.AddField(
            model_name='motorista',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_categoria',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh_numero',
            field=models.CharField(default='A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
